# Generated by Django 5.2 on 2025-04-09 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mealtime', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], default='Breakfast', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='Enter Name or Number', max_length=255)),
                ('physical', models.CharField(default='Body Plan', max_length=255)),
                ('spiritual', models.CharField(default='Spiritual Needs', max_length=255)),
                ('emotional', models.CharField(default='Emotional Needs', max_length=255)),
                ('mental', models.CharField(default='Support System', max_length=255)),
                ('quality', models.CharField(default='Fulfillment', max_length=255)),
                ('goals', models.CharField(default='Future Aspirations', max_length=255)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylife.meal')),
            ],
        ),
    ]
