# Generated by Django 5.2 on 2025-04-13 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='myplan',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
