# Generated by Django 5.2 on 2025-04-13 17:13

import django.db.models.deletion
import mylife.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0003_myplan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplan',
            name='user',
            field=models.ForeignKey(default=mylife.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
